"""
PA#4 — Modes of Operation: CBC, OFB, Randomized CTR.

All modes use AES_PRF from PA#2 as the block cipher E_k.

Dependencies:
    - crypto.pa02_prf (AES_PRF)
    - crypto.pa03_cpa_enc (pad_message, unpad_message)
    - crypto.utils
"""

from crypto.pa02_prf import AES_PRF
from crypto.pa03_cpa_enc import pad_message, unpad_message, BLOCK_SIZE
from crypto.utils import random_bytes, xor_bytes, bytes_to_int, int_to_bytes


# ============================================================
# CBC Mode
# ============================================================

def cbc_encrypt(key: bytes, message: bytes, iv: bytes = None,
                aes: AES_PRF = None) -> tuple[bytes, bytes]:
    """
    CBC mode encryption.

    Returns:
        (iv, ciphertext)
    """
    aes = aes or AES_PRF()
    iv = iv or random_bytes(BLOCK_SIZE)
    padded = pad_message(message)
    blocks = [padded[i:i + BLOCK_SIZE] for i in range(0, len(padded), BLOCK_SIZE)]

    prev = iv
    ct_blocks = []
    for mi in blocks:
        ci = aes.encrypt_block(key, xor_bytes(prev, mi))
        ct_blocks.append(ci)
        prev = ci

    return (iv, b''.join(ct_blocks))


def cbc_decrypt(key: bytes, iv: bytes, ciphertext: bytes,
                aes: AES_PRF = None) -> bytes:
    """
    CBC mode decryption.
    """
    aes = aes or AES_PRF()
    blocks = [ciphertext[i:i + BLOCK_SIZE] for i in range(0, len(ciphertext), BLOCK_SIZE)]

    prev = iv
    pt_blocks = []
    for ci in blocks:
        mi = xor_bytes(aes.decrypt_block(key, ci), prev)
        pt_blocks.append(mi)
        prev = ci

    return unpad_message(b''.join(pt_blocks))


# ============================================================
# OFB Mode
# ============================================================

def ofb_encrypt(key: bytes, message: bytes, iv: bytes = None,
                aes: AES_PRF = None) -> tuple[bytes, bytes]:
    """
    OFB mode encryption.
    Keystream is generated by chaining E_k on the IV.
    Encryption and decryption are identical.

    Returns:
        (iv, ciphertext)
    """
    aes = aes or AES_PRF()
    iv = iv or random_bytes(BLOCK_SIZE)
    padded = pad_message(message)
    blocks = [padded[i:i + BLOCK_SIZE] for i in range(0, len(padded), BLOCK_SIZE)]

    o = iv
    ct_blocks = []
    for mi in blocks:
        o = aes.encrypt_block(key, o)  # Generate keystream block
        ci = xor_bytes(o, mi)
        ct_blocks.append(ci)

    return (iv, b''.join(ct_blocks))


def ofb_decrypt(key: bytes, iv: bytes, ciphertext: bytes,
                aes: AES_PRF = None) -> bytes:
    """
    OFB mode decryption. Identical to encryption (XOR is its own inverse).
    """
    aes = aes or AES_PRF()
    blocks = [ciphertext[i:i + BLOCK_SIZE] for i in range(0, len(ciphertext), BLOCK_SIZE)]

    o = iv
    pt_blocks = []
    for ci in blocks:
        o = aes.encrypt_block(key, o)
        mi = xor_bytes(o, ci)
        pt_blocks.append(mi)

    return unpad_message(b''.join(pt_blocks))


# ============================================================
# Randomized CTR Mode
# ============================================================

def ctr_encrypt(key: bytes, message: bytes, nonce: bytes = None,
                aes: AES_PRF = None) -> tuple[bytes, bytes]:
    """
    Randomized Counter mode encryption.

    Returns:
        (nonce, ciphertext)
    """
    aes = aes or AES_PRF()
    nonce = nonce or random_bytes(BLOCK_SIZE)
    padded = pad_message(message)
    blocks = [padded[i:i + BLOCK_SIZE] for i in range(0, len(padded), BLOCK_SIZE)]

    nonce_int = bytes_to_int(nonce)
    ct_blocks = []
    for i, mi in enumerate(blocks):
        counter = nonce_int + i
        counter_bytes = int_to_bytes(counter, BLOCK_SIZE)
        ci = xor_bytes(aes.encrypt_block(key, counter_bytes), mi)
        ct_blocks.append(ci)

    return (nonce, b''.join(ct_blocks))


def ctr_decrypt(key: bytes, nonce: bytes, ciphertext: bytes,
                aes: AES_PRF = None) -> bytes:
    """CTR decryption. Same as encryption (XOR is its own inverse)."""
    aes = aes or AES_PRF()
    blocks = [ciphertext[i:i + BLOCK_SIZE] for i in range(0, len(ciphertext), BLOCK_SIZE)]

    nonce_int = bytes_to_int(nonce)
    pt_blocks = []
    for i, ci in enumerate(blocks):
        counter = nonce_int + i
        counter_bytes = int_to_bytes(counter, BLOCK_SIZE)
        mi = xor_bytes(aes.encrypt_block(key, counter_bytes), ci)
        pt_blocks.append(mi)

    return unpad_message(b''.join(pt_blocks))


# ============================================================
# Unified API
# ============================================================

def encrypt(mode: str, key: bytes, message: bytes,
            iv_or_nonce: bytes = None) -> tuple[bytes, bytes]:
    """Unified encryption API. mode: 'CBC', 'OFB', or 'CTR'."""
    mode = mode.upper()
    if mode == 'CBC':
        return cbc_encrypt(key, message, iv=iv_or_nonce)
    elif mode == 'OFB':
        return ofb_encrypt(key, message, iv=iv_or_nonce)
    elif mode == 'CTR':
        return ctr_encrypt(key, message, nonce=iv_or_nonce)
    else:
        raise ValueError(f"Unknown mode: {mode}. Use CBC, OFB, or CTR.")


def decrypt(mode: str, key: bytes, iv_or_nonce: bytes,
            ciphertext: bytes) -> bytes:
    """Unified decryption API."""
    mode = mode.upper()
    if mode == 'CBC':
        return cbc_decrypt(key, iv_or_nonce, ciphertext)
    elif mode == 'OFB':
        return ofb_decrypt(key, iv_or_nonce, ciphertext)
    elif mode == 'CTR':
        return ctr_decrypt(key, iv_or_nonce, ciphertext)
    else:
        raise ValueError(f"Unknown mode: {mode}. Use CBC, OFB, or CTR.")


# ============================================================
# Attack Demonstrations
# ============================================================

def cbc_iv_reuse_attack() -> dict:
    """
    CBC IV reuse attack: same IV + same first block → same first ciphertext block.
    """
    from crypto.utils import random_bytes
    key = random_bytes(16)
    iv = random_bytes(16)

    # Two messages with same first block
    m1 = b'A' * 16 + b'B' * 16
    m2 = b'A' * 16 + b'C' * 16

    _, ct1 = cbc_encrypt(key, m1, iv=iv)
    _, ct2 = cbc_encrypt(key, m2, iv=iv)

    c1_block1 = ct1[:16]
    c2_block1 = ct2[:16]

    return {
        'c1': ct1.hex(),
        'c1_prime': ct2.hex(),
        'blocks_match': c1_block1 == c2_block1,
        'explanation': (
            "CBC: E_k(IV XOR M1) is identical for both messages since M1 and IV are the same. "
            "IV reuse leaks equality of plaintext blocks."
        ),
    }


def ofb_keystream_reuse_attack() -> dict:
    """
    OFB keystream reuse: if same IV is used twice, XOR of ciphertexts = XOR of plaintexts.
    """
    from crypto.utils import random_bytes
    key = random_bytes(16)
    iv = random_bytes(16)

    m1 = b'Hello, World!!!!'
    m2 = b'Secret message!!'

    _, c1 = ofb_encrypt(key, m1, iv=iv)
    _, c2 = ofb_encrypt(key, m2, iv=iv)

    # c1 = m1 XOR ks, c2 = m2 XOR ks
    # c1 XOR c2 = m1 XOR m2
    # Take first block (m1 and m2 are exactly 1 block after padding would be 2, use raw)
    # Actually both are 16 bytes = 1 block, padded to 2 blocks
    # Use first 16 bytes to compare
    c1_xor_c2 = xor_bytes(c1[:16], c2[:16])
    m1_xor_m2 = xor_bytes(m1, m2)

    recovered_m2 = xor_bytes(m1, c1_xor_c2)

    return {
        'm1': m1.decode(),
        'm2': m2.decode(),
        'c1_xor_c2': c1_xor_c2.hex(),
        'm1_xor_m2': m1_xor_m2.hex(),
        'match': c1_xor_c2 == m1_xor_m2,
        'recovered_m2': recovered_m2.hex(),
    }


def bit_flip_error_propagation() -> dict:
    """
    Demonstrate error propagation in each mode when a ciphertext bit is flipped.
    """
    from crypto.utils import random_bytes

    key = random_bytes(16)
    # 3-block message (48 bytes → after padding = 64 bytes = 4 blocks)
    # Use exactly 32 bytes (2 blocks) → padded to 3 blocks
    msg = b'Block1__16bytes!' + b'Block2__16bytes!' + b'Block3__16bytes!'

    results = {}

    for mode_name, enc_fn, dec_fn in [
        ('cbc', cbc_encrypt, cbc_decrypt),
        ('ofb', ofb_encrypt, ofb_decrypt),
        ('ctr', ctr_encrypt, ctr_decrypt),
    ]:
        iv, ct = enc_fn(key, msg)

        # Flip a bit in the SECOND block of ciphertext (block index 1)
        ct_list = bytearray(ct)
        ct_list[BLOCK_SIZE] ^= 0x01  # Flip bit in byte 0 of block 1
        tampered_ct = bytes(ct_list)

        try:
            recovered = dec_fn(key, iv, tampered_ct)
        except ValueError:
            # Padding error — CBC might cause this if block 3 gets garbled
            # Treat all blocks as corrupted
            recovered = b'\xff' * len(msg)

        corrupted = []
        for i in range(min(len(msg), len(recovered)) // BLOCK_SIZE):
            orig_block = msg[i * BLOCK_SIZE:(i + 1) * BLOCK_SIZE]
            rec_block = recovered[i * BLOCK_SIZE:(i + 1) * BLOCK_SIZE]
            if orig_block != rec_block:
                corrupted.append(i)

        results[mode_name] = {'corrupted_blocks': corrupted}

    return results
